### ISSUE TITLE
Is there any enhancement to find the navigation bet. place outside to a place inside ? 

### ISSUE THREAD

**Issue by mahmoudadel54** [ayush-saklani/navit#2]
Fist of all, I would like to thank you for this great effort and the amazing output. Really great work.

I wonder if there any enhancement can be applied to find the path from a place outside [or my live location] to a place inside.
![image](https://github.com/user-attachments/assets/8bbf0a7f-9cd4-4f1f-b8e5-d411c74a3ad5)

**Comment by ayush-saklani** [comment]
hmmm..
First of all, Thankyou for such kind words. 
Secondly i have some ideas to implement before this as this will not that amount of value to this project as other add-on will. 
but i have an idea how to do this, by using some kind of router that can use the OSM data to lead to the building gate and then we can use the internal data for internal routing and connecting both the system.

**Comment by mahmoudadel54** [comment]
> hmmm.. First of all, Thankyou for such kind words. Secondly i have some ideas to implement before this as this will not that amount of value to this project as other add-on will. but i have an idea how to do this, by using some kind of router that can use the OSM data to lead to the building gate and then we can use the internal data for internal routing and connecting both the system.

Good point 
thanks a lot
